kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: drill-rb
subjects:
  - kind: ServiceAccount
    name: drill-sa
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: drill-role
  apiGroup: rbac.authorization.k8s.io

